server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: data-service
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8
    username: root
    password: xiaohua00
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    timeout: 100000
  cache:
    redis:
      time-to-live: 10000
logging:
  level:
    root: info
mybatis:
  type-aliases-package:  com.skylan.dataservice.domain
  mapper-locations: classpath:mapper/*.xml