server:
  port: 5555
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: 163
          uri: http://www.163.com/
          predicates:
            - Path=/163/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
           - Path=/USER-SERVICE/**


feign:
  hystrix:
    enabled: true

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

